### PR TITLE
Second branch

### PR DESCRIPTION
**Pull request by rida-elbahtouri**
all the old reviews is on this link:
https://github.com/rida-elbahtouri/rida-aye-youtube/pull/5
I merged that pull request by mistake that why I created a new pull request.

### CODE REVIEW

**Comment by lucasmazo32** [comment]
# Pull Request under review :telescope:

**Comment by lucasmazo32** [comment]
# Changes required :wrench:

You are doing a great job so far, and the project is looking good. For the project to get approved kindly implement these changes:

## Required changes:

- [ ] The subscribe button should be a button, not an image.

- [ ] Try to vertically align the navbar.
> Screenshot from your page
image

You are close, please implement these changes and submit them for another code review!

### Happy coding! :computer:

## Lucas Mazo

**Comment by trekab** [comment]
# Changes Required!
Hi @rida-elbahtouri and @Alaska01, I commend you on including the link to the last review in your PR description. In order to wrap things up let's work on the following changes;
- [ ] Increase the size of the main video section appropriately so that the big blank space on the right is eliminated. This will make [your clone](https://raw.githack.com/rida-elbahtouri/rida-aye-youtube/second-branch/ind) look more like the [original](https://www.youtube.com/watch?v=-7Q031SOjWc).
- [ ] 'Subscribe' should be a button, not an image.
- [x] Position the icons in the main video section appropriately. "Number of views", "SubscrIbe", "like/dislike", and "share" are currently in the wrong positions.

__Please work on the changes above and submit another code review__
__Treasure Kabareebe__

**Comment by rida-elbahtouri** [comment]
we are cloning this page:
https://archive.vn/Bss88
this is the list of project requirement:
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi Team 👋

### Welcome to Microverse🚀

Your project looks quite ok. you both did well on this.

However, we need to fix this to move on:

- [ ] Kindly watch [this screencast](https://www.loom.com/share/16890eae644e443490437041ce3be885) to know the changes to be made and fix the issues outlined there.

Once you are done fixing the issues and please request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by Dandush03** [comment]
# :red_circle: Status Require: changes :muscle: 
### Hey :wave: 
## Good attempts on this one :muscle: :+1: 

## Here are the issues to address to get the project meet the requirement:wink:

# Description

## Project Specification
Don't forget that this project consists of building an HTML document that matches the appearance of this [YouTube video player page](http://archive.vn/Bss88).

Check it [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/)

-------------------------------------------

### Page structure

-------------------------------------------
#### Navigation bar

##### Left Part
- [ ] Logo not properly aligned

##### Center
- [ ] Input should be wider
- [ ] Search Button should have the same input size

##### Right
- [ ] There should be only an upload button and a blue "Sign In" one
- [ ] "Sign In" is not properly aligned


-------------------------------------------

#### Require:
Screenshot from 2020-05-07 08-14-35

#### Yours:
Screenshot from 2020-05-07 08-54-13

-------------------------------------------

#### Video

##### Description

- [ ] Missing section

-------------------------------------------

#### Require:
Screenshot from 2020-05-07 08-20-45

#### Yours:
Screenshot from 2020-05-07 08-48-05

-------------------------------------------

### Sidebar Recommended videos

- [ ] "Autoplay" and Toggle button should be aligned to the right
- [ ] Needs more padding

-------------------------------------------

#### Require:
Screenshot from 2020-05-07 08-28-54

#### Yours:
Screenshot from 2020-05-07 08-48-18

-------------------------------------------

### Footer

#### There should be a FOOTER section

-------------------------------------------

#### Require:
Screenshot from 2020-05-07 08-52-31

-------------------------------------------

## Kindly address all these changes and submit a new code review


### Happy coding:computer: 

#### Daniel Laloush

**Comment by rida-elbahtouri** [comment]
we added the footer and the video description
**PN**:
check this file if the nav-bar does not align in your browser
https://docs.google.com/document/d/1gvTHDam87npJrCvHY_CGvcc1uGWTyofCr8mEJ83sW9Q/edit?usp=sharing

**Review by trekab — APPROVED** [review]
# Project Approved! :tada: 
Well done __team__! :clap: 
_All the best on your next projects!_
__Treasure Kabareebe__

**Pull request merged**
